image: gitpod/workspace-mongodb
tasks:
  - name: MongoDB
    init: mkdir -p /home/gitpod/db
    command: mongod --dbpath /home/gitpod/db
  - name: App
    init: |
      mkdir -p /home/gitpod/.hydro
      echo '{"host":"127.0.0.1","port":"27017","name":"hydro","username":"","password":""}' >/home/gitpod/.hydro/config.json && \
      nvm install 18
      nvm use 18
      nvm alias default 18
      yarn
      yarn build:ui:production
      npx hydrooj cli system set server.port 2333
      npx hydrooj cli user create root@hydro.local root rootroot 2
      npx hydrooj cli user setSuperAdmin 2
    command: yarn debug
    env:
      DEFAULT_STORE_PATH: /home/gitpod/file
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - vscode-icons-team.vscode-icons
    - samuelcolvin.jinjahtml
    - tabnine.tabnine-vscode
    - gruntfuggly.todo-tree
    - ryanluker.vscode-coverage-gutters
