apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
  labels:
    app: backend
  namespace: hydro-namespace
data:
  addon.json: |-
    {{.Values.Backend.AddonJson | nindent 4}}

  config.json: |-
    {{.Values.Backend.ConfigJson | nindent 4}}
