apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hydro-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
  namespace: hydro-namespace
spec:
  rules:
    - host: "backend.boo.foo" # 如果不需要当然也可以去掉HostName
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service-service
                port:
                  name: backend-cluster-endpoint
