version: '3.7'

services:
    
  # Warning: mongodb here is not password-protected.
  # DO NOT EXPOSE THIS SERVICE TO THE PUBLIC.
  oj-mongo:
    image: mongo
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db

  oj-backend:
    build: ./backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-mongo
    volumes:
      - ./data/file:/data/file
      - ./data/backend:/root/.hydro
    ports:
      - "0.0.0.0:80:8888" # In docker mode, change THIS port instead of port in system settings!

  oj-judge:
    build: ./judge
    container_name: oj-judge
    restart: always
    privileged: true
    depends_on:
      - oj-backend
    volumes:
      - ./data/judge:/root/.config/hydro
